const assetUrl = (path) => `${import.meta.env.BASE_URL}${path}`;

export const electricianProfile = {
  id: 'electrician',
  brand: {
    name: 'אורי לוי',
    businessName: 'אורי לוי — חשמל פרימיום',
    descriptor: 'חשמלאי מוסמך לבתים ולעסקים',
    sampleDisclosure: 'אתר הדגמה — כל השמות, ההסמכות, המחירים ופרטי הקשר הם תוכן לדוגמה בלבד.',
  },
  theme: {
    colors: {
      midnight: '#101820',
      navy: '#162633',
      surface: '#F4F0E8',
      copper: '#B56A3B',
      amber: '#F3B23C',
    },
    direction: 'rtl',
    language: 'he',
  },
  navigation: [
    { label: 'שירותים', href: '#services' },
    { label: 'פרויקטים', href: '#projects' },
    { label: 'מחירים', href: '#packages' },
    { label: 'אודות', href: '#about' },
    { label: 'שאלות ותשובות', href: '#faq' },
    { label: 'יצירת קשר', href: '#contact' },
  ],
  hero: {
    eyebrow: 'חשמל מקצועי, בטוח ושקוף',
    headline: 'חשמל בטוח. עבודה מדויקת. שקט אמיתי.',
    description: 'שירות חשמל קפדני לבתים ולעסקים, עם אבחון ברור, תיאום מסודר וגימור נקי.',
    primaryAction: 'קבלו הצעת מחיר',
    phoneAction: 'התקשרו עכשיו',
    whatsappAction: 'שלחו WhatsApp',
    image: assetUrl('profiles/electrician/hero-electrician.webp'),
    imageAlt: 'חשמלאי מקצועי בסביבת מגורים מודרנית — תמונת הדגמה',
  },
  trust: [
    { title: 'בטיחות ללא פשרות', text: 'עבודה מסודרת לפי נהלי בטיחות ובדיקות סיום.' },
    { title: 'אבחון מדויק', text: 'הסבר בהיר של התקלה והפתרון לפני תחילת העבודה.' },
    { title: 'שקיפות במחיר', text: 'הצעת מחיר מסודרת ואישור לפני כל שינוי.' },
    { title: 'עמידה בזמנים', text: 'תיאום חלון הגעה ועדכון אם התנאים משתנים.' },
  ],
  services: [
    { id: 'faults', title: 'איתור ותיקון תקלות', description: 'אבחון קצרים, עומסים ותקלות חוזרות.', cta: 'לתיאום אבחון' },
    { id: 'panels', title: 'לוחות חשמל', description: 'שדרוג, חלוקה וסימון מסודר של לוחות.', cta: 'לבדיקת הלוח' },
    { id: 'lighting', title: 'התקנת נקודות ותאורה', description: 'תכנון והתקנה נקייה למרחבי מגורים ועבודה.', cta: 'לתכנון התקנה' },
    { id: 'ev', title: 'הכנה לעמדות טעינה', description: 'בדיקת תשתית והכנה מקצועית לעמדת טעינה.', cta: 'לבדיקת התאמה' },
    { id: 'smart-home', title: 'בתים חכמים', description: 'תשתיות, בקרים ותרחישי תאורה נוחים.', cta: 'לייעוץ ראשוני' },
    { id: 'business', title: 'תחזוקת עסקים', description: 'טיפול מונע ותיקונים למשרדים ולחנויות.', cta: 'לבניית מסלול שירות' },
  ],
  projects: [
    { title: 'שדרוג לוח בדירה', type: 'מגורים', challenge: 'לוח ישן ללא סימון', result: 'חלוקה ברורה ותשתית מוכנה להרחבה', service: 'panels', image: assetUrl('profiles/electrician/project-panel.webp') },
    { title: 'תאורה אדריכלית', type: 'בית פרטי', challenge: 'מספר אזורי תאורה', result: 'תרחישים נוחים וגימור נקי', service: 'lighting', image: assetUrl('profiles/electrician/project-lighting.webp') },
    { title: 'הכנה לעמדת טעינה', type: 'חניה משותפת', challenge: 'מרחק מהלוח הראשי', result: 'תוואי מסודר ומוגן', service: 'ev', image: assetUrl('profiles/electrician/project-ev.webp') },
    { title: 'בקרת בית חכם', type: 'דירה חדשה', challenge: 'ריבוי מערכות', result: 'שליטה מאוחדת ונוחה', service: 'smart-home', image: assetUrl('profiles/electrician/project-smart-home.webp') },
  ],
  testimonials: [
    { name: 'נועה, רמת גן', quote: 'הגיע בתיאום, הסביר כל שלב והשאיר את הבית נקי.', sample: true },
    { name: 'אייל, גבעתיים', quote: 'אבחון יסודי פתר תקלה שחזרה במשך חודשים.', sample: true },
    { name: 'מיכל, תל אביב', quote: 'תקשורת מצוינת ותוצאה מדויקת בתכנון התאורה.', sample: true },
    { name: 'דניאל, קריית אונו', quote: 'מחיר ברור מראש ועבודה מקצועית ומסודרת.', sample: true },
    { name: 'יעל, פתח תקווה', quote: 'שירות אדיב וגימור מוקפד בכל נקודה.', sample: true },
  ],
  packages: [
    { name: 'ביקור ואבחון', price: 'החל מ־250 ₪', description: 'בדיקה ראשונית והסבר מקצועי', sample: true },
    { name: 'נקודת חשמל', price: 'החל מ־380 ₪', description: 'התקנה בתנאים סטנדרטיים', sample: true },
    { name: 'בדיקת לוח', price: 'החל מ־450 ₪', description: 'בדיקה, סימון והמלצות מסודרות', sample: true },
  ],
  professional: {
    heading: 'נעים להכיר, אורי',
    biography: 'חשמלאי מוסמך בדיוני עם גישה שירותית וקפדנית לפרויקטים בבתים ובעסקים.',
    portrait: assetUrl('profiles/electrician/about-ori.webp'),
    portraitAlt: 'דיוקן מקצועי של אורי לוי — דמות ותמונה לדוגמה',
    stats: [{ label: 'שנות ניסיון', value: '12+' }, { label: 'פרויקטים', value: '600+' }],
    credentials: ['רישיון חשמלאי מוסמך — מספר לדוגמה', 'ביטוח מקצועי — פרט לדוגמה', 'אחריות כתובה בהתאם לסוג העבודה — נוסח לדוגמה'],
  },
  serviceArea: {
    heading: 'אזורי שירות וזמינות',
    areas: ['תל אביב', 'רמת גן', 'גבעתיים', 'פתח תקווה', 'קריית אונו', 'בקעת אונו'],
    hours: 'ימים א׳–ה׳ 08:00–18:00, יום ו׳ בתיאום מראש',
    urgentNote: 'למקרה דחוף אפשר להתקשר ולבדוק זמינות; אין התחייבות לזמן הגעה מדויק.',
    sample: true,
  },
  faq: [
    { question: 'איך נקבע המחיר?', answer: 'מחיר סופי נקבע לאחר אבחון, בהתאם להיקף העבודה ולתשתית הקיימת.' },
    { question: 'האם יש שירות לקריאות דחופות?', answer: 'אפשר להתקשר ולבדוק זמינות נקודתית, ללא התחייבות לזמן הגעה.' },
    { question: 'האם החשמלאי מוסמך?', answer: 'באתר אמיתי יוצגו רישיון בתוקף ופרטי הסמכה; הנתונים כאן הם לדוגמה.' },
    { question: 'האם ניתנת אחריות?', answer: 'האחריות מוגדרת בכתב לפי סוג העבודה והציוד.' },
    { question: 'איך להתכונן לביקור?', answer: 'מומלץ לפנות גישה ללוח ולרשום מתי התקלה מופיעה.' },
    { question: 'איך מאתרים תקלה?', answer: 'מתחילים בתשאול ובבדיקות מדורגות כדי לצמצם את מקור הבעיה.' },
    { question: 'האם אתם מתקינים מערכות בית חכם?', answer: 'כן, לאחר בדיקת התאמה של התשתית והמערכות הרצויות.' },
    { question: 'מה נדרש לעמדת טעינה?', answer: 'נדרשת בדיקת לוח, עומסים, תוואי והנחיות היצרן.' },
    { question: 'באילו אזורים ניתן השירות?', answer: 'אזורי השירות לדוגמה מפורטים באתר, וזמינות נבדקת בעת הפנייה.' },
  ],
  contact: {
    heading: 'בואו נדבר על העבודה הבאה',
    phone: '+972-50-555-0147',
    phoneDisplay: '050-555-0147',
    whatsapp: '972505550147',
    email: 'hello@ori-electric-demo.example',
    location: 'מרכז ישראל — כתובת לדוגמה',
    whatsappMessage: 'שלום אורי, אשמח לקבל פרטים על שירות חשמל.',
    sample: true,
  },
  leadForm: {
    heading: 'קבלת הצעת מחיר',
    submitLabel: 'שליחת הפרטים',
    fields: {
      fullName: { label: 'שם מלא', required: true },
      phone: { label: 'טלפון', required: true },
      workType: { label: 'סוג העבודה', required: true },
      area: { label: 'אזור או עיר', required: true },
      urgency: { label: 'דחיפות', required: true },
      description: { label: 'תיאור קצר', required: false },
    },
    workTypes: ['תקלה', 'לוח חשמל', 'תאורה ונקודות', 'עמדת טעינה', 'בית חכם', 'תחזוקת עסק', 'אחר'],
    urgencyOptions: ['רגיל', 'בימים הקרובים', 'דחוף — לבדיקת זמינות'],
    demoStorageKey: 'professional-services-demo-leads',
  },
  seo: {
    title: 'אורי לוי — חשמלאי מוסמך במרכז | אתר הדגמה',
    description: 'שירותי חשמל מקצועיים לדוגמה במרכז: תקלות, לוחות, תאורה, עמדות טעינה ובתים חכמים.',
    canonicalUrl: 'https://delevski.github.io/professional-services-template/',
    socialImage: assetUrl('profiles/electrician/social-preview.webp'),
    favicon: assetUrl('profiles/electrician/favicon.svg'),
    locale: 'he_IL',
  },
};
